### ISSUE TITLE
Slowing Down the Floating Text

### ISSUE THREAD

**Issue by Echtelion17** [serhiy/libgdx-floating-text-example#1]
Hi Serhiy,

First of all, I am very thankful about your work on floating text. 

However you defined deltaX and deltaY to control the speed of floating, I can't get it. These guys are defining where my text to go, but nothing about speed. Text is too fast man. :) 

I tried to change "TimeUnit.SECONDS.toMillis" , but it solved nothing. I know I look like a rookie, but I'm. I'd really appreciated if you can direct me to solution.

**Comment by Echtelion17** [comment]
Oo I'm too dumb. I did it 5 seconds after I post this message above. 

I just couldn't think about to change the FloatingText class. Changed 1000f to 10000f solved my case. I'm really sorry to create this dumby question here.

**Comment by serhiy** [comment]
@Echtelion17  sorry for not being able to reply before, I am on vacation now, glad you managed to solve the problem.

**Comment by Echtelion17** [comment]
No problem, I'm still thankful :). By the way, I have a small question for you: How can I have a floating text like in the beginning of Star Wars movies? Can I have a deltaZ, or should I do something else?

**Comment by serhiy** [comment]
@Echtelion17 I am not really sure how that can be done, since at the moment I do not explore the 3D capabilities of LibGDX. If you would like to continue using Stage one possible (not necessarily easy) solution could be rendering a 3D rotated text to a FrameBuffer, convert it into the Image and render as an actor, but at the moment I do not have such examples/snippets.

**Comment by Echtelion17** [comment]
Understood. I've got an advice about using "perspective camera", I am working on it right now. Anyway, you helped a lot thank you very much Serhiy.
